name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Check Git and Directory Configuration
        run: |
          echo "Setting up git safe directory..."
          git config --global --add safe.directory /home/ubuntu/actions-meadhikari/_work/server/server
          echo "Checking permissions for checkout directory..."
          sudo chmod -R 777 /home/ubuntu/actions-meadhikari/_work/server
          ls -la /home/ubuntu/actions-meadhikari/_work/server

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false # Disable this if the error is due to permission issues
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Check and set directory permissions
      - name: Check and Set Permissions
        run: |
          echo "Checking directory permissions..."
          ls -ld /home/ubuntu/actions-meadhikari/_work/server/server
          echo "Setting directory ownership and permissions..."
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-meadhikari/_work/server/server
          sudo chmod -R 755 /home/ubuntu/actions-meadhikari/_work/server/server

      # Navigate to the server directory and install dependencies
      - name: Clean and Install Dependencies
        run: |
          echo "Navigating to server directory..."
          cd /home/ubuntu/actions-meadhikari/_work/server/server
          echo "Removing old node_modules and package-lock.json..."
          sudo rm -rf node_modules package-lock.json
          echo "Installing new dependencies..."
          sudo npm install --no-optional --timeout=50000 --verbose
          echo "Successfully added new dependencies..."

      # Start the server if it's not running, otherwise restart it
      - name: Start or Restart Server
        run: |
          if pm2 status | grep -q 'server'; then
            echo "Restarting server..."
            cd /home/ubuntu/actions-meadhikari/_work/server/server
            pm2 restart server.js
          else
            echo "Starting server..."
            cd /home/ubuntu/actions-meadhikari/_work/server/server
            pm2 start server.js
          fi
