# This workflow will do a clean installation of node dependencies, cache/restore them, and restart the server using PM2.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # Temporarily disabling cache for troubleshooting purposes
        cache: false

    # Clean install dependencies by removing old node_modules and package-lock.json
    - name: Clean install dependencies
      run: |
        sudo rm -rf node_modules package-lock.json
        df -h   # Check disk usage to ensure there's enough space
        npm install --force   # Force install dependencies to handle any lingering issues

    # Restart the server using pm2
    - name: Restart Server with PM2
      run: pm2 start server.js
